### PR TITLE
:bug: Adjust e2e test after the repo structure has changed

### LINKED ISSUE #133: Adjust e2e test after the structure of this repo has changed
/kind bug

After the structure of this repository has changed, we need to adjust the e2e test.

Related to https://github.com/SovereignCloudStack/cluster-stacks/pull/131

### PR DESCRIPTION
**Pull request by michal-gubricky**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #133 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

**Comment by michal-gubricky** [comment]
> Build failed (e2e-quick-test pipeline). https://zuul.scs.community/t/SCS/buildset/0c70cb8f45ba49e9b5a0f05f4726ed0c
> 
> ❌ [e2e-openstack-quick ](https://zuul.scs.community/t/SCS/build/5925325e168d45d9bb1c6b55bd99c2cd) **FAILURE** in 18m 42s

Obtained weird error:
```
error reconciling the Cluster topology: failed to create OpenStackMachineTemplate.infrastructure.cluster.x-k8s.io
```

**Comment by michal-gubricky** [comment]
> Build failed (e2e-quick-test pipeline). https://zuul.scs.community/t/SCS/buildset/0c7e05be0b4a4c3d93a5b307dbf8fb23
> 
> ❌ [e2e-openstack-quick ](https://zuul.scs.community/t/SCS/build/8d45d8b0c178448c8e3ec07d9de9faaf) **FAILURE** in 14m 37s

Current if only fails because of this error:
```
2024-07-10 11:48:56.617359 | ubuntu-jammy | E0710 11:44:49.489051       1 reconcile_state.go:1233] "Failed to create object" err="failed to create typed patch object (default/test-cluster-r25zc; infrastructure.cluster.x-k8s.io/v1beta1, Kind=OpenStackMachineTemplate): .spec.template.spec.serverGroupID: field not declared in schema" controller="topology/cluster" controllerGroup="cluster.x-k8s.io" controllerKind="Cluster" Cluster="default/test-cluster" namespace="default" name="test-cluster" reconcileID="5ecd0730-354a-499b-9976-3c7053b36f29" resource={"group":"infrastructure.cluster.x-k8s.io","version":"v1beta1","resource":"OpenStackMachineTemplate"} OpenStackMachineTemplate="default/test-cluster-r25zc" OpenStackMachineTemplate="default/test-cluster-r25zc"
```
but after rebasing this branch with the main. It should work.

**Comment by michal-gubricky** [comment]
> Build failed (e2e-quick-test pipeline). https://zuul.scs.community/t/SCS/buildset/36f231c83e1f477e98658d82d4356632
> 
> ❌ [e2e-openstack-quick ](https://zuul.scs.community/t/SCS/build/e4653917742f4b8d8216f815278a8b55) **FAILURE** in 21m 48s

The pipeline failed on the sonobuoy tests, which is not related to this issue #133 
```
sonobuoy run --plugin-env=e2e.E2E_PROVIDER=openstack --mode=quick
time="2024-07-10T14:07:15Z" level=error msg="Preflight checks failed"
time="2024-07-10T14:07:15Z" level=error msg="no dns pods found with the labels [k8s-app=kube-dns, k8s-app=coredns] in namespace kube-system"
```

**Comment by michal-gubricky** [comment]
> Build failed (e2e-quick-test pipeline). https://zuul.scs.community/t/SCS/buildset/e651cdb2415f42299ec522fbd8e59583
> 
> ❌ [e2e-openstack-quick ](https://zuul.scs.community/t/SCS/build/82b10e2f1f68473495f1b75c7351d1ff) **FAILURE** in 15m 34s

The template `cluster.yaml.j2` needs to be changed as machineDeployments was renamed, see https://github.com/SovereignCloudStack/cluster-stacks/commit/3e7c580595fd3899d85655c744df72ac6c252462

**Comment by chess-knight** [comment]
> > Build failed (e2e-quick-test pipeline). https://zuul.scs.community/t/SCS/buildset/e651cdb2415f42299ec522fbd8e59583
> > ❌ [e2e-openstack-quick ](https://zuul.scs.community/t/SCS/build/82b10e2f1f68473495f1b75c7351d1ff) **FAILURE** in 15m 34s
> 
> The template `cluster.yaml.j2` needs to be changed as machineDeployments were renamed, see [3e7c580](https://github.com/SovereignCloudStack/cluster-stacks/commit/3e7c580595fd3899d85655c744df72ac6c252462)

I merged changes after a failed build. It looks like we have the same problem as in KaaSv1 and should be fixed also here, see https://github.com/SovereignCloudStack/k8s-cluster-api-provider/pull/621

**Pull request merged**
