### PR TITLE
Add quickstart guide

### PR DESCRIPTION
**Pull request by paulphys**

### CODE REVIEW

**Review by chess-knight — APPROVED** [review]
Overall LGTM, just two minor comments

**Review by michal-gubricky — COMMENTED** [review]
Overall LGTM. I think we should also have a quickstart guide for docker and only one quickstart guide per provider. That means, we will have all quickstart guides in cluster-stacks repo(maybe make most sense) or in provider operators repos. What do you think @paulphys ?

**Comment by paulphys** [comment]
@michal-gubricky Once we have more than one provider that would definitely be the right way to go, but we really only support openstack right now. @jschoone Are there any plans to further support docker?

**Comment by michal-gubricky** [comment]
> @michal-gubricky Once we have more than one provider that would definitely be the right way to go, but we really only support openstack right now. @jschoone Are there any plans to further support docker?

AFAIK, docker is supported natively by the cso. But I do not know about the future plans for the docker.

**Pull request merged**
