### PR TITLE
:sparkles: Add hetzner baremetal cluster stack

### LINKED ISSUE #108: Cluster Stacks for Hetzner
/kind feature

**Describe the solution you'd like**
Title says all

### PR DESCRIPTION
**Pull request by chess-knight**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #108

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

**Comment by chess-knight** [comment]
Hi @janiskemper. As discussed in the chat, I added you as the reviewer because you are an expert on Hetzner. This is the first version of pure Hetzner baremetal clusterstack(control plane and worker nodes in robot, loadbalancer in the hcloud). The manifests are mostly taken from CAPH(without machine health checks and remediation), but I read that it is only for demonstration purposes. Maybe we can collaborate here, and tune this cluster stack by removing/adding/editing kubeadm settings or cluster variables, playing with cluster addons(e.g. cilium values are taken from CAPH, and CCM from syself/charts) and so on. Thanks

**Comment by janiskemper** [comment]
Thanks @chess-knight ! One thing you can maybe look at: The CCM we use still mainly is our fork under the syself organization. However, hetzner supports bare metal in the upstream one as well for some time now. You need to configure it in a certain way, but I believe that there should be some documentation about it. If not, you can surely open an issue and ask for it. 

This might be a better option for SCS, since our fork usually lacks behind a bit ;)

Otherwise, I would really advice you to integrate custom remediation and MHC. There are a lot of cases where a reboot of the machine fixes it already, especially with bare metal.

**Comment by chess-knight** [comment]
> Otherwise, I would really advice you to integrate custom remediation and MHC. There are a lot of cases where a reboot of the machine fixes it already, especially with bare metal.

Right now, the remediationTemplate cannot be added to the cluster stacks(clusterclass), because you need to know the namespace of HetznerBareMetalRemediationTemplate in advance. I fixed it upstream https://github.com/kubernetes-sigs/cluster-api/pull/10843 but we have to wait for the merge and release.
Until the upstream patch, the user can specify MHC in Cluster.spec.topology in the same way(the user will know the namespace of HetznerBareMetalRemediationTemplate in advance).

**Comment by chess-knight** [comment]
> Thanks @chess-knight ! One thing you can maybe look at: The CCM we use still mainly is our fork under the syself organization. However, hetzner supports bare metal in the upstream one as well for some time now. You need to configure it in a certain way, but I believe that there should be some documentation about it. If not, you can surely open an issue and ask for it.
> 
> This might be a better option for SCS, since our fork usually lacks behind a bit ;)

Hi @janiskemper, I tried to replace Syself's hccm with Hetzner's but one thing doesn't work out of the box. CAPH is setting providerID field `hcloud://bm-$SERVER_NUMBER` for the machines and hccm is setting `hrobot://$SERVER_NUMBER` for the nodes. Then IMO CAPI cannot finish joining worker nodes, because the providerID field is different. E.g. it doesn't remove CABPK taint `node.cluster.x-k8s.io/uninitialized:NoSchedule`, see also https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/611 which is maybe related. I am falling into this https://github.com/kubernetes-sigs/cluster-api/blob/v1.7.3/internal/controllers/machine/machine_controller_noderef.go#L80.

**Comment by janiskemper** [comment]
There is a config I believe. Someone from Hetzner tried this out and uses it. But I don't know where to find it

**Comment by chess-knight** [comment]
> There is a config I believe. Someone from Hetzner tried this out and uses it. But I don't know where to find it

If I see correctly, everything is hardcoded:
- CAPH hardcodes it here https://github.com/syself/cluster-api-provider-hetzner/blob/main/pkg/services/baremetal/baremetal/baremetal.go#L895
- HCCM hardcodes it here https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/internal/providerid/providerid.go#L67

Right now the only way I see is to manually change it for all hetznerbaremetalmachines with e.g. `KUBE_EDITOR="sed -i 's#hcloud://bm-#hrobot://#'" kubectl edit hetznerbaremetalmachine`

**Comment by janiskemper** [comment]
search for "prefixRobotLegacy" in the providerid.go. I just had a quick look at the links you provided

**Comment by chess-knight** [comment]
> search for "prefixRobotLegacy" in the providerid.go. I just had a quick look at the links you provided

Yeah I see, but it is there only for migration purposes and not used for the new nodes. Instead "prefixRobot" is used.

**Comment by janiskemper** [comment]
I don't know, sorry. I know that they got it running, but I don't know how exactly it works. I haven't tried. You can open an issue I guess and ask for a short guide to use the hcloud ccm with CAPH bare metal

**Comment by chess-knight** [comment]
Hi @janiskemper, can you recheck this PR, please?

**Pull request merged**
