### PR TITLE
fix(cluster-class): options from different api versions somehow mixed up

### LINKED ISSUE #129: Changes from v1alpha7 to v1beta1 not present in openstack-scs Cluster Stacks
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubernetes version: (use `kubectl version`)
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by jschoone**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #129 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

```ZUUL_CONFIG
cluster_stack = "providers/openstack/scs"
```

### CODE REVIEW

**Comment by jschoone** [comment]
Hi @chess-knight and @DEiselt could you have a look if theres something left and/or I made something wrong?
My first tests worked so far

**Review by chess-knight — COMMENTED** [review]
LGTM, I have only one small finding so far.

**Review by DEiselt — APPROVED** [review]
LGTM aside from @chess-knight's comment

**Comment by michal-gubricky** [comment]
> Build failed (e2e-quick-test pipeline). https://zuul.scs.community/t/SCS/buildset/e1ab5fb1ad3840f29feba4097a6c968b
> 
> ❌ [e2e-openstack-quick ](https://zuul.scs.community/t/SCS/build/2d6a350a1cbb467683cef2f9c7abf378) **FAILURE** in 10m 53s

Ah, based on the last run, it seems the infrastructure running the Zuul tests is slow, as it takes over 3 minutes for pods in the kube-system to be ready in the kind cluster that is usually not a problem. I will try to run this pipeline later today.

**Comment by michal-gubricky** [comment]
> Build failed (e2e-quick-test pipeline). https://zuul.scs.community/t/SCS/buildset/468aceff46cc4c21a75a820ca9fdc681
> 
> ❌ [e2e-openstack-quick ](https://zuul.scs.community/t/SCS/build/8cff742cf4f14ee6bcfd72b1ae21c4e0) **FAILURE** in 41m 56s

Based on this failed pipeline and further investigation, we need to adjust the e2e tests, as the structure of this repository has changed. I will create an issue and start working on that.

**Pull request merged**
